INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',1,'al-Fatihah','The Opening');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',2,'al-Baqarah','The Cow');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',3,'Al-Imran','The Family Of Imran');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',4,'an-Nisa','Women');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',5,'al-Maidah','The Food');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',6,'al-Anam','The Cattle');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',7,'al-Araf','The Elevated Places');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',8,'al-Anfal','The Spoils Of War');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',9,'at-Taubah','Repentance');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',10,'Yunus','Jonah');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',11,'Hud','Hud');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',12,'Yusuf','Joseph');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',13,'ar-Rad','The Thunder');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',14,'Ibrahim','Abraham');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',15,'al-Hijr','The Rock');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',16,'an-Nahl','The Bee');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',17,'Al-Isra','The Night Journey');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',18,'al-Kahf','The Cave');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',19,'Maryam','Mary');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',20,'Ta Ha','Ta Ha');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',21,'al-Anbiya','The Prophets');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',22,'al-Hajj','The Pilgrimage');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',23,'al-Muminun','The Believers');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',24,'an-Nur','The Light');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',25,'al-Furqan','The Criterion');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',26,'ash-Shuara','The Poets');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',27,'an-Naml','The Ant');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',28,'al-Qasas','The Narrative');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',29,'al-Ankabut','The Spider');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',30,'ar-Rum','The Romans');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',31,'Luqman','Lukman');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',32,'as-Sajdah','The Adoration');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',33,'al-Ahzab','The Allies');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',34,'Saba','Sheba');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',35,'Fatir','The Creator');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',36,'Ya Sin','Ya Sin');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',37,'as-Saffat','The Rangers');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',38,'Sad','Sad');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',39,'az-Zumar','The Companies');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',40,'Ghafir','The Forgiving One');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',41,'Fussilat','Revelations Well Expounded');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',42,'ash-Shura','The Counsel');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',43,'az-Zukhruf','The Embellishment');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',44,'ad-Dukhan','The Evident Smoke');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',45,'al-Jathiyah','The Kneeling');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',46,'al-Ahqaf','The Sandhills');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',47,'Muhammad','Muhammad');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',48,'al-Fath','The Victory');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',49,'al-Hujurat','The Chambers');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',50,'Qaf','Qaf');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',51,'ad-Dhariyat','The Scatterers');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',52,'at-Tur','The Mountain');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',53,'an-Najm','The Star');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',54,'al-Qamar','The Moon');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',55,'ar-Rahman','The Merciful');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',56,'al-Waqiah','That Which is Coming');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',57,'al-Hadid','The Iron');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',58,'al-Mujadilah','She Who Pleaded');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',59,'al-Hashr','The Exile');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',60,'al-Mumtahanah','She Who is Tested');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',61,'as-Saff','The Ranks');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',62,'al-Jumuah','The Day of Congregation');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',63,'al-Munafiqun','The Hypocrites');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',64,'at-Taghabun','The Cheating');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',65,'at-Talaq,','The Divorce');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',66,'at-Tahrim','The Prohibition');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',67,'al-Mulk','The Kingdom');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',68,'al-Qalam','The Pen');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',69,'al-Haqqah','The Inevitable');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',70,'al-Maarij','The Ladders');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',71,'Nuh','Noah');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',72,'al-Jinn','The Jinn');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',73,'al-Muzammil','The Mantled One');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',74,'al-Mudathir','The Clothed One');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',75,'al-Qiyamah','The Resurrection');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',76,'al-Insane','The Man');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',77,'al-Mursalat','The Emissaries');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',78,'an-Naba','The Tidings');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',79,'an-Naziat','Those Who Pull Out');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',80,'Abasa','He Frowned');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',81,'at-Takwir','The Cessation');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',82,'al-Infitar','The Cleaving Asunder');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',83,'Al-Mutaffifeen','The Defrauders');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',84,'al-Inshiqaq','The Rending');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',85,'al-Buruj','the Constellations');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',86,'at-Tariq','The Night-Comer');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',87,'al-Ala','The Most High');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',88,'al-Ghashiya','The Overwhelming Calamity');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',89,'al-Fajr','The Dawn');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',90,'al-Balad','The City');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',91,'ash-Shams','The Sun');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',92,'al-Layl','The Night');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',93,'ad-Duha','The Early Hours');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',94,'ash-Sharh','The Expansion');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',95,'at-Tin','The Fig');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',96,'al-Alaq','The Clot');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',97,'al-qadr','The Majesty');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',98,'al-Bayyinah','The Proof');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',99,'Az-Zalzala','The Shaking');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',100,'al-Adiyat','The Assaulters');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',101,'al-Qariah','The Terrible Calamity');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',102,'at-Takathur','Worldly Gain');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',103,'al-Asr','Time');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',104,'al-Humazah','The Slanderer');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',105,'al-Fil','The Elephant');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',106,'al-Quraish','The Quraish');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',107,'al-Maun','The Daily Necessaries');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',108,'al-Kauthar','Abundance');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',109,'al-Kafirun','The Unbelievers');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',110,'an-Nasr','The Help');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',111,'Al-Masad','The Palm Fibre');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',112,'al-Ikhlas','The Unity');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',113,'al-Falaq','The Daybreak');
INSERT INTO `contents`(`id`, `SuraID`, `Name`,`English`) VALUES ('',114,'an-Nas','The Men');
